### ISSUE TITLE
plot_dimred error when cell numbers is larger than 1000 and hex_cells is numeric 

### ISSUE THREAD

**Issue by lixin4306ren** [dynverse/dynplot#42]
Error information:
```
Scale for 'fill' is already present. Adding another scale for 'fill', which will replace the
existing scale.
Error: Discrete value supplied to continuous scale
```

the command I used:
```
plot_dimred(
  model_slingshot, 
  expression_source = hy10_dataset$expression, 
  color_cells = "feature",
  feature_oi = "CD34",
  color_density = "grouping",
  grouping = y,
  label_milestones = FALSE,
)
```
If set `color_density` none or set `hex_cells` False, there is no error.

**Comment by zouter** [comment]
Hi @lixin4306ren 

I managed to reproduce the error, but in the current state it is really difficult to fix. It's a bit tricky to get two color scales to work in ggplot2, and it goes wrong in several cases like this one...
To handle these cases, we're moving development to a much more modular package called dynplot2 . Rather than using one monolithic function, it will export several layers and scales to build your plot from the ground up. We have some prototypes but nothing final yet. I hope to be able to work on it this month if time allows, so stay tuned!
