### ISSUE TITLE
Node and arrow size for plot dimred with trajectory

### ISSUE THREAD

**Issue by ghar1821** [dynverse/dynplot#49]
Hi guys,

Love the package! Really like the way the dimred plots are drawn.

I'm just wondering if it's possible to have parameters that control the milestone node size and the arrow sizes? I can currently do it by downloading and sourcing the source codes, but it'll be nice to not have to do this all the time.

Thanks!

**Comment by rcannood** [comment]
Hello Givanna,

Thanks for the kind words :) 

I made a few changes to dynplot in the devel branch so that you can change the sizes as follows: 
```r
plot_dimred(
  example_bifurcating, 
  size_milestones = 10, 
  size_transitions = 3, 
  arrow = grid::arrow(length = grid::unit(1, "cm"), type = "closed")
)
```

I notice that for high values of `size_transitions`, the edges start to break down. I will look into fixing this in the future. 

In the meantime, could you update dynplot by running `remotes::install_github("dynverse/dynplot@devel")` to see if the recent changes have solved your problem?

Kind regards,
Robrecht

**Comment by rcannood** [comment]
I'm closing this issue as the example shown above should have resolved it. Feel free to post an update if this is not the case.
